[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos_m2v_pipeline"
dynamic = ["version"]
description = "Model2Vec intent engine for OVOS"
readme = "README.md"
license = { text = "Apache License 2.0" }
authors = [{ name = "TigreGoticoLda", email = "jarbasai@mailfence.com" }]
maintainers = [{ name = "OpenVoiceOS" }]

[project.urls]
Homepage = "https://openvoiceos.org"
Repository = "https://github.com/TigreGotico/ovos-m2v-pipeline"
Funding = "https://nlnet.nl/project/OpenVoiceOS"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Text Processing :: Linguistic",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "ovos-workshop>=0.1.7,<9.0.0",
    "ovos-plugin-manager>=0.5.0,<3.0.0",
    "ovos-bus-client",
    "ovos-config",
    "ovos-utils>=0.3.4,<1.0.0",
    "model2vec[inference]",
]

[project.entry-points."opm.pipeline"]
ovos-m2v-pipeline = "ovos_m2v_pipeline:Model2VecIntentPipeline"

[tool.setuptools]
packages = ["ovos_m2v_pipeline"]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "ovos_m2v_pipeline.version.__version__" }
