name: Run Tests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_m2v_pipeline/version.py'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  push:
    branches:
      - dev
    paths-ignore:
      - 'ovos_m2v_pipeline/version.py'
      - 'requirements/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev
          python -m pip install build wheel uv pytest pytest-cov
      - name: Install core repo
        run: |
          uv pip install --system -e .
      - name: Run tests
        run: |
          pytest --cov=ovos_core --cov-report xml tests/
